name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.17.x', '1.18.x']
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: check fmt
        run: make fmt-check
        env:
          GOPATH: ${{ runner.workspace }}
      - name: static program analysis
        uses: golangci/golangci-lint-action@v3
      - name: build
        run: make build
        env:
          GOPATH: ${{ runner.workspace }}
      - name: test
        run: make test
        env:
          GOPATH: ${{ runner.workspace }}
      - name: coverage
        run: bash <(curl -s https://codecov.io/bash)