name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.19.x' ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: static program analysis
        uses: golangci/golangci-lint-action@v3
      - name: build
        run: go build -o gostruct2openapi ./cmd/doc
        env:
          GOPATH: ${{ runner.workspace }}
      - name: test
        run: go test ./...
        env:
          GOPATH: ${{ runner.workspace }}